### PR TITLE
Fix reference error for certain fonts

### LINKED ISSUE #282: ReferenceError: Cannot access 'c3x' before initialization
Version 1.9.0-2.0.2 introduced a regression in the `parse()` function. I'm getting the following error and stack trace with the attached OTF font. It works fine in 1.8.1.

```
/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:11520
                                    c3x = c2x + stack.shift();
                                        ^

ReferenceError: Cannot access 'c3x' before initialization
    at parse (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:11520:41)
    at $7ee0705195f3b047$export$2e2bcd8739ae039._getPath (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:11570:9)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.get path (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:10750:21)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.descriptor.get (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:92:29)
    at $7ee0705195f3b047$export$2e2bcd8739ae039._getCBox (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:10685:21)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.get cbox (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:10735:21)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.descriptor.get (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:92:29)
    at $7ee0705195f3b047$export$2e2bcd8739ae039._getMetrics (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:10706:72)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.get advanceWidth (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:10764:21)
    at $7ee0705195f3b047$export$2e2bcd8739ae039.descriptor.get (/test-fontkit/2.0.2/node_modules/fontkit/dist/main.cjs:92:29)
```

[KeplerStd-Bold.otf.zip](https://github.com/foliojs/fontkit/files/8958815/KeplerStd-Bold.otf.zip)

Use the following repo to reproduce: https://github.com/fstrube/fontkit-test

### PR DESCRIPTION
**Pull request by fstrube**
Fixes #282.

This branch fixes a ReferenceError that gets thrown when parsing certain fonts, including the Playfair Display font that is in the fontkit repository. The error started happening when version 1.9.0 of fontkit was released.

```
     ReferenceError: Cannot access 'c3x' before initialization
```

The fix involved refactoring the `parse()` function to use block-scoping inside the switch case statements in that function. See [the MDN docs on redeclarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#redeclarations).

### CODE REVIEW

**Comment by Pomax** [comment]
It might make sense to preallocate all the variables outside the switch, as that would have been the effective behaviour when babel transpiled to `var` (due to hoisting) anyway.

**Comment by fstrube** [comment]
@Pomax @blikblum I preallocated all the variables outside the switch as you suggested. The diff is much smaller, which is nice.

File: src/glyph/CFFGlyph.js [hunk 1]
```diff
@@ -125,34 +129,34 @@ export default class CFFGlyph extends Glyph {
...
-              let subr = subrs[index];
+
+            case 10: // callsubr
+              index = stack.pop() + subrsBias;
+              subr = subrs[index];
               if (subr) {
                 usedSubrs[index] = true;
-                let p = stream.pos;
-                let e = end;
+                var p = stream.pos;
```
Comment (Pomax) [inline src/glyph/CFFGlyph.js:150]: `var` get hoisted, so definitely want to keep these `let` (obeying block scope)

File: src/glyph/CFFGlyph.js [hunk 2]
```diff
@@ -254,79 +258,78 @@ export default class CFFGlyph extends Glyph {
...
-              let index = stack.pop() + gsubrsBias;
-              let subr = gsubrs[index];
+            case 29: // callgsubr
+              index = stack.pop() + gsubrsBias;
+              subr = gsubrs[index];
               if (subr) {
                 usedGsubrs[index] = true;
-                let p = stream.pos;
-                let e = end;
+                var p = stream.pos;
```
Comment (Pomax) [inline src/glyph/CFFGlyph.js:319]: these will want to stay `let` as well

**Review by Pomax — CHANGES_REQUESTED** [review]
I don't have PR merging powers, but happy to review.

**Comment by fstrube** [comment]
Thanks for reviewing @Pomax! I made those two changes that you suggested.

There are also a few more instances of `var` declarations in that function. 

* [Line 474](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L474)
* [Line 484](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L484)
* [Line 585](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L585)
* [Line 588](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L588)

Do you think it is worth changing them to `let`? Or should we leave them as is to avoid any unexpected behavior?

**Comment by Pomax** [comment]
Any opportunity to move from scope-hoisting to block scoped vars is a good opportunity I'd say, but I'll let @devongovett decide whether that's something he would like to see in this PR.

**Comment by fstrube** [comment]
Hi @devongovett, would you mind taking a look at this? It is causing most of our pdfkit projects that rely on OTF fonts to fail. I'm hoping we can get this merged in soon, then get https://github.com/foliojs/pdfkit/pull/1367 updated and merged as well.

**Review by devongovett — APPROVED** [review]
Thanks!

**Comment by AlainGourves** [comment]
It is possible to make a new release with this PR ?
The latest version is 2.0.2, released on June 19 2022 before this PR, so the error 

```
ReferenceError: Cannot access 'c3x' before initialization
```
still occurs (for example with the font `PlayfairDisplay-Regular.otf` found in `/test/data/PlayfairDisplay`).

Thanks in advance!
