### PR TITLE
Fixes getting path from woff files with CFF

### LINKED ISSUE #199: CFF glyph parsing doesn’t work with WOFF
The problem [is here](https://github.com/foliojs/fontkit/blob/1a53baa0cb6205fbdb63b2243416c400a03e7d0f/src/glyph/CFFGlyph.js#L27). This sets up `stream` to be `this._font`, which is a stream representing the whole font file. In a regular OTF, this works because the offsets in `cff.topDict.CharStrings` are global (that is, relative to the beginning of the font file).

However this is apparently not true in WOFF — the offsets in `cff.topDict.CharStrings` are relative to the beginning of the `CFF ` table.

The fix is to check if `this._font` is a WOFF font, and if so, use the `CFF ` table stream as the value for `stream` (instead of `this._font` itself).

### PR DESCRIPTION
**Pull request by blikblum**
Fixes #199 

Uses stream from CFF table instead of font one which does not match in woff fonts

### CODE REVIEW

File: test/glyphs.js [hunk 1]
```diff
@@ -155,56 +155,101 @@ describe('glyphs', function() {
...
+      it('should get a WOFF2Glyph', function() {
+        return assert.equal(glyph.constructor.name, 'WOFF2Glyph');
+      });
 
-    it('should get the glyph cbox', function() {
-      let glyph = font.glyphsForString('T')[0];
-      return assert.deepEqual(glyph.cbox, new BBox(28, 0, 508, 656));
-    });
+      it('should get a path for the glyph', function() {
+        let tglyph = font.glyphsForString('T')[0];
```
Comment (Pomax) [inline test/glyphs.js]: `let` is blocked scoped, so probably worth keeping it `glyph` rather than naming it `tglyph`, purely for consistency

File: test/glyphs.js [hunk 2]
```diff
@@ -155,56 +155,101 @@ describe('glyphs', function() {
...
+      return assert.equal(glyph.path.toSVG(), 'M90 0L90 656L254 656Q406 656 485 571.5Q564 487 564 331Q564 174 485.5 87Q407 0 258 0ZM173 68L248 68Q363 68 420.5 137.5Q478 207 478 331Q478 455 420.5 521.5Q363 588 248 588L173 588Z');
     });
+  });
 
-    it('should get the glyph name', function() {
-      let glyph = font.glyphsForString('T')[0];
-      return assert.equal(glyph.name, 'T');
-    });
+  describe('WOFF otf glyphs', function() {
+      let font = fontkit.openSync(__dirname + '/data/SourceSansPro/SourceSansPro-Regular.otf.woff');
```
Comment (Pomax) [inline test/glyphs.js]: I don't think there's a prettifier running for the source at the moment, but it looks like this got indented twice.

File: test/glyphs.js [hunk 3]
```diff
@@ -155,56 +155,101 @@ describe('glyphs', function() {
...
+
+      it('should get a cubic path for the glyph', function() {
+        return assert.equal(glyph.path.toSVG(), 'M90 0L258 0C456 0 564 122 564 331C564 539 456 656 254 656L90 656ZM173 68L173 588L248 588C401 588 478 496 478 331C478 165 401 68 248 68Z');
+      });
   });
 
-  describe('WOFF2 glyph', function() {
-    let font = fontkit.openSync(__dirname + '/data/SourceSansPro/SourceSansPro-Regular.woff2');
+  describe('WOFF2 ttf glyph', function() {
+      let font = fontkit.openSync(__dirname + '/data/SourceSansPro/SourceSansPro-Regular.ttf.woff2');
```
Comment (Pomax) [inline test/glyphs.js]: looks like there's double indentation here, too.

File: test/glyphs.js [hunk 4]
```diff
@@ -155,56 +155,101 @@ describe('glyphs', function() {
...
+        return assert.deepEqual(glyph.cbox, expectedBox);
+      });
+
+      it('should get the ttf glyph bbox', function() {
+        return assert.deepEqual(glyph.bbox, expectedBox);
+      });
+  });  
+
+  describe('WOFF2 otf glyph', function() {
+      let font = fontkit.openSync(__dirname + '/data/SourceSansPro/SourceSansPro-Regular.otf.woff2');
```
Comment (Pomax) [inline test/glyphs.js]: looks like there's double indentation here, too
